// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz1KH5IBMFg9Yy-ns3NeQUGClaSv1jJiQ',
    appId: '1:222228087920:web:d647aa0e4f54f9ce1760b5',
    messagingSenderId: '222228087920',
    projectId: 'eco-leul',
    authDomain: 'eco-leul.firebaseapp.com',
    storageBucket: 'eco-leul.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkIpm49fEAU9Lqyxxg1DW8Zg9SvsLg8iI',
    appId: '1:222228087920:android:cb3c0247990ff8051760b5',
    messagingSenderId: '222228087920',
    projectId: 'eco-leul',
    storageBucket: 'eco-leul.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEoi-xzcOawPDB2t_jiWOxQrelqlo9P6Q',
    appId: '1:222228087920:ios:ed6f8ae236d28b181760b5',
    messagingSenderId: '222228087920',
    projectId: 'eco-leul',
    storageBucket: 'eco-leul.firebasestorage.app',
    iosBundleId: 'com.example.loginFire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEoi-xzcOawPDB2t_jiWOxQrelqlo9P6Q',
    appId: '1:222228087920:ios:ed6f8ae236d28b181760b5',
    messagingSenderId: '222228087920',
    projectId: 'eco-leul',
    storageBucket: 'eco-leul.firebasestorage.app',
    iosBundleId: 'com.example.loginFire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz1KH5IBMFg9Yy-ns3NeQUGClaSv1jJiQ',
    appId: '1:222228087920:web:c02c54d32cb5dc9c1760b5',
    messagingSenderId: '222228087920',
    projectId: 'eco-leul',
    authDomain: 'eco-leul.firebaseapp.com',
    storageBucket: 'eco-leul.firebasestorage.app',
  );
}
